/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uc.seng301.petbattler.asg3.unittests;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void notARealTest() {
        Assertions.assertTrue(true);
    }
}
