@startuml
hide empty members

interface Iterator<T> {
    +boolean hasNext()
    +T next()
}

class BookIterator implements Iterator<Book> {
    -List<Book> books
    -int position = 0
    +BookIterator(List<Book> books)
    +boolean hasNext()
    +Book next()
}

interface BookCollection {
    +Iterator<Book> createIterator()
}

class Bookshelf implements BookCollection {
    -List<Book> books = new ArrayList<>()
    +void addBook(Book book)
    +Iterator<Book> createIterator()
}

class Book {
    -String title
    +Book(String title)
    +String getTitle()
}


Bookshelf "1" *-- "0..*" Book
Bookshelf o-- BookIterator
BookIterator *-- Book

Client -> Book: creates


@enduml
