@startuml
hide empty members
interface Image {
    +display()
}

class RealImage implements Image {
    -String filename
    +RealImage(String filename)
    +display()
    -loadImageFromDisk()
}

class ProxyImage implements Image {
    -RealImage realImage
    -String filename
    +ProxyImage(String filename)
    +display()
}

ProxyImage o-- RealImage
Client -> ProxyImage: uses
@enduml